/*
   This file was generated automatically by Alchitry Labs version 1.2.1.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module adder16bit_14 (
    input [3:0] alufn,
    input [15:0] a,
    input [15:0] b,
    output reg [15:0] out,
    output reg z,
    output reg v,
    output reg n
  );
  
  
  
  reg [15:0] sum;
  
  reg [15:0] xb;
  
  reg [1:0] code;
  
  always @* begin
    code[0+0-:1] = alufn[0+0-:1];
    code[1+0-:1] = alufn[3+0-:1];
    
    case (code)
      2'h0: begin
        sum = $signed(a) + $signed(b);
      end
      2'h1: begin
        sum = $signed(a) - $signed(b);
      end
      2'h2: begin
        sum = $signed(a) * $signed(b);
      end
      2'h3: begin
        sum = $signed(a) / $signed(b);
      end
      default: begin
        sum = 1'h0;
      end
    endcase
    if (sum == 1'h0) begin
      z = 1'h1;
    end else begin
      z = 1'h0;
    end
    n = sum[15+0-:1];
    out = sum;
    xb = b ^ alufn[0+0-:1];
    v = (a[15+0-:1] & xb[15+0-:1] & ~sum[15+0-:1]) + (~a[15+0-:1] & ~xb[15+0-:1] & sum[15+0-:1]);
  end
endmodule
