/*
   This file was generated automatically by Alchitry Labs version 1.2.1.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module au_top_0 (
    input clk,
    input rst_n,
    output reg [7:0] led,
    input usb_rx,
    output reg usb_tx,
    output reg [23:0] io_led,
    output reg [7:0] io_seg,
    output reg [3:0] io_sel,
    input [4:0] io_button,
    input [23:0] io_dip
  );
  
  
  
  reg rst;
  
  wire [1-1:0] M_reset_cond_out;
  reg [1-1:0] M_reset_cond_in;
  reset_conditioner_1 reset_cond (
    .clk(clk),
    .in(M_reset_cond_in),
    .out(M_reset_cond_out)
  );
  wire [(2'h2+0)-1:0] M_buttoncond_out;
  reg [(2'h2+0)-1:0] M_buttoncond_in;
  
  genvar GEN_buttoncond0;
  generate
  for (GEN_buttoncond0=0;GEN_buttoncond0<2'h2;GEN_buttoncond0=GEN_buttoncond0+1) begin: buttoncond_gen_0
    button_conditioner_2 buttoncond (
      .clk(clk),
      .in(M_buttoncond_in[GEN_buttoncond0*(1)+(1)-1-:(1)]),
      .out(M_buttoncond_out[GEN_buttoncond0*(1)+(1)-1-:(1)])
    );
  end
  endgenerate
  wire [(2'h2+0)-1:0] M_buttondetector_out;
  reg [(2'h2+0)-1:0] M_buttondetector_in;
  
  genvar GEN_buttondetector0;
  generate
  for (GEN_buttondetector0=0;GEN_buttondetector0<2'h2;GEN_buttondetector0=GEN_buttondetector0+1) begin: buttondetector_gen_0
    edge_detector_3 buttondetector (
      .clk(clk),
      .in(M_buttondetector_in[GEN_buttondetector0*(1)+(1)-1-:(1)]),
      .out(M_buttondetector_out[GEN_buttondetector0*(1)+(1)-1-:(1)])
    );
  end
  endgenerate
  wire [16-1:0] M_fsmRUN_aluOut;
  wire [32-1:0] M_fsmRUN_displayOUT;
  wire [6-1:0] M_fsmRUN_opOUT;
  reg [2-1:0] M_fsmRUN_button;
  reg [24-1:0] M_fsmRUN_in;
  fsm_COMBINE_4 fsmRUN (
    .clk(clk),
    .rst(rst),
    .button(M_fsmRUN_button),
    .in(M_fsmRUN_in),
    .aluOut(M_fsmRUN_aluOut),
    .displayOUT(M_fsmRUN_displayOUT),
    .opOUT(M_fsmRUN_opOUT)
  );
  wire [7-1:0] M_seg_seg;
  wire [4-1:0] M_seg_sel;
  reg [32-1:0] M_seg_values;
  multi_seven_seg_5 seg (
    .clk(clk),
    .rst(rst),
    .values(M_seg_values),
    .seg(M_seg_seg),
    .sel(M_seg_sel)
  );
  
  always @* begin
    M_reset_cond_in = ~rst_n;
    rst = M_reset_cond_out;
    usb_tx = usb_rx;
    led = 8'h00;
    M_buttoncond_in = io_button[3+1-:2];
    M_buttondetector_in = M_buttoncond_out;
    M_fsmRUN_button = M_buttondetector_out;
    M_fsmRUN_in = io_dip;
    io_led[0+7-:8] = M_fsmRUN_aluOut[0+7-:8];
    io_led[8+7-:8] = M_fsmRUN_aluOut[8+7-:8];
    io_led[16+7-:8] = M_fsmRUN_opOUT;
    M_seg_values = M_fsmRUN_displayOUT;
    io_seg = ~M_seg_seg;
    io_sel = ~M_seg_sel;
  end
endmodule
