/*
   This file was generated automatically by Alchitry Labs version 1.2.1.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module fsm_AUTO_8 (
    input clk,
    input rst,
    input [1:0] button,
    input [23:0] in,
    output reg [15:0] aluOut,
    output reg [31:0] displayOUT
  );
  
  
  
  always @* begin
    aluOut = 16'hffff;
    displayOUT = 32'h0b111200;
  end
endmodule
